quartz:
  #quartz相关属性配置
  properties:
    org:
      quartz:
        datasource: #配置数据库源（org.quartz.dataSource.qzDS.maxConnections: c3p0配置的是有s的，druid数据源没有s）
          qzDS:
            connectionProvider:
              class: com.cbw.quartz02.util.DruidConnectionProvider
            driver: com.mysql.jdbc.Driver
            URL: jdbc:mysql://192.168.31.5:3306/ry?useUnicode=true&characterEncoding=utf8
            user: root
            password: 123456
            maxConnection: 10
        scheduler:
          instanceName: clusteredScheduler #调度器的实例名
          instanceId: AUTO #调度器编号自动生成
          makeSchedulerThreadDaemon: true
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          tablePrefix: qrtz_ #数据库表名前缀
          isClustered: true #开启分布式部署
          clusterCheckinInterval: 10000 #分布式节点有效性检查时间间隔,单位:秒
          useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool #自带的线程池实现类
          threadCount: 10 #开启10个线程
          threadPriority: 5 #工作者线程的优先级
          threadsInheritContextClassLoaderOfInitializingThread: true
          makeThreadsDaemons: true # 指定在线程池里面创建的线程是否是守护线程
  #数据库方式
  job-store-type: jdbc
  #初始化表结构
  jdbc:
  initialize-schema: never
