spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
logging:
  config: classpath:log4j2.xml

#指定映射xml文件位置
#classpath对应resource，*.xml表示配置mapper下所有xml文件
mybatis:
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappings/modules/*/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.rlc.rlcfmbapi.modules.fmb.entity,com.rlc.rlcfmbapi.modules.cmdb.entity
    # 支持通过 Mapper 接口参数来传递分页参数
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
